[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_dapp_todo = "3po4TvdNdTRgnwYH4LFB5HviQydScKK58LrSDpSEWmSf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/roy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
